"""add_installation_requests_and_recipient_center

Revision ID: 13fce828266e
Revises: 5512ac126304
Create Date: 2026-06-03 14:45:33.260927

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13fce828266e"
down_revision = "5512ac126304"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installation_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("center_name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("zip_code", sa.String(length=10), nullable=False),
        sa.Column("contact_name", sa.String(length=100), nullable=False),
        sa.Column("contact_role", sa.String(length=100), nullable=True),
        sa.Column("contact_email", sa.String(length=254), nullable=False),
        sa.Column("contact_phone", sa.String(length=30), nullable=True),
        sa.Column("motivation", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_by_id", sa.Integer(), nullable=True),
        sa.Column("created_center_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_center_id"], ["centers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["processed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("installation_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_installation_requests_status"), ["status"], unique=False
        )

    with op.batch_alter_table("mailing_recipients", schema=None) as batch_op:
        batch_op.add_column(sa.Column("center_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_mailing_recipients_center_id"), ["center_id"], unique=False
        )
        batch_op.create_foreign_key(None, "centers", ["center_id"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mailing_recipients", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_mailing_recipients_center_id"))
        batch_op.drop_column("center_id")

    with op.batch_alter_table("installation_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_installation_requests_status"))

    op.drop_table("installation_requests")
    # ### end Alembic commands ###
