"""add_center_map_fields

Revision ID: 5356e317757e
Revises: 13fce828266e
Create Date: 2026-06-03 19:09:51.243346

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5356e317757e"
down_revision = "13fce828266e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("centers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("latitude", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("longitude", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("pathology", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("target_audience", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("centers", schema=None) as batch_op:
        batch_op.drop_column("target_audience")
        batch_op.drop_column("pathology")
        batch_op.drop_column("longitude")
        batch_op.drop_column("latitude")

    # ### end Alembic commands ###
