"""add website field to events

Revision ID: 5512ac126304
Revises: 0024
Create Date: 2026-05-08 21:12:42.174307

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5512ac126304"
down_revision = "0024"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("website", sa.String(length=500), nullable=True))

    with op.batch_alter_table("inbound_emails", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_inbound_emails_generated_task_id",
            "tasks",
            ["generated_task_id"],
            ["id"],
            ondelete="SET NULL",
            use_alter=True,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email_lower"))
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index(
            batch_op.f("ix_users_email_lower"),
            [sa.literal_column("lower(email::text)")],
            unique=True,
        )

    with op.batch_alter_table("inbound_emails", schema=None) as batch_op:
        batch_op.drop_constraint("fk_inbound_emails_generated_task_id", type_="foreignkey")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("website")

    # ### end Alembic commands ###
